// Cloudflare Pages Function — /api/deploy
// Deploys a stored project to GitHub, then cleans up R2

export interface Env {
  PROJECTS_BUCKET: R2Bucket;
}

interface DeployBody {
  projectId: string;
  githubToken: string;
  repoName: string;
  repoDescription?: string;
  isPrivate?: boolean;
}

interface ProjectFile {
  path: string;
  content: string;
}

interface StoredProject {
  name: string;
  description: string;
  projectType: string;
  stack: string;
  files: ProjectFile[];
}

interface GitHubRepo {
  full_name: string;
  html_url: string;
  name: string;
}

function corsHeaders(): HeadersInit {
  return {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type',
  };
}

const GITHUB_API = 'https://api.github.com';
const USER_AGENT = 'GitForge-AI/1.0';

function githubHeaders(token: string): HeadersInit {
  return {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github.v3+json',
    'Content-Type': 'application/json',
    'User-Agent': USER_AGENT,
    'X-GitHub-Api-Version': '2022-11-28',
  };
}

async function createRepository(
  token: string,
  name: string,
  description: string,
  isPrivate: boolean
): Promise<GitHubRepo> {
  const res = await fetch(`${GITHUB_API}/user/repos`, {
    method: 'POST',
    headers: githubHeaders(token),
    body: JSON.stringify({
      name,
      description: description || `Generated by GitForge AI`,
      private: isPrivate,
      auto_init: false,
      has_issues: true,
      has_projects: false,
      has_wiki: false,
    }),
  });

  if (!res.ok) {
    const body = await res.json().catch(() => ({})) as any;
    const msg = body?.message ?? res.statusText;
    if (res.status === 422 && msg.toLowerCase().includes('already exist')) {
      throw new Error(`Repository "${name}" already exists in your GitHub account. Please choose a different name.`);
    }
    if (res.status === 401) {
      throw new Error('GitHub token is invalid or expired. Please provide a valid personal access token with "repo" scope.');
    }
    if (res.status === 403) {
      throw new Error('GitHub token does not have permission to create repositories. Ensure the token has the "repo" scope.');
    }
    throw new Error(`Failed to create GitHub repository: ${msg}`);
  }

  return res.json() as Promise<GitHubRepo>;
}

async function uploadFile(
  token: string,
  fullName: string,
  path: string,
  content: string,
  commitMessage: string
): Promise<void> {
  // Base64 encode content safely (handle unicode)
  let encoded: string;
  try {
    // Handle binary-safe base64 via Uint8Array
    const bytes = new TextEncoder().encode(content);
    let binary = '';
    for (let i = 0; i < bytes.length; i++) {
      binary += String.fromCharCode(bytes[i]);
    }
    encoded = btoa(binary);
  } catch {
    encoded = btoa(unescape(encodeURIComponent(content)));
  }

  const res = await fetch(`${GITHUB_API}/repos/${fullName}/contents/${encodeURIComponent(path)}`, {
    method: 'PUT',
    headers: githubHeaders(token),
    body: JSON.stringify({
      message: commitMessage,
      content: encoded,
    }),
  });

  if (!res.ok) {
    const body = await res.json().catch(() => ({})) as any;
    throw new Error(`Failed to upload "${path}": ${body?.message ?? res.statusText}`);
  }
}

async function uploadFilesSequentially(
  token: string,
  fullName: string,
  files: ProjectFile[]
): Promise<{ uploaded: number; failed: string[] }> {
  let uploaded = 0;
  const failed: string[] = [];

  // Upload files in batches of 3 for better throughput without hitting rate limits
  const batchSize = 3;

  for (let i = 0; i < files.length; i += batchSize) {
    const batch = files.slice(i, i + batchSize);
    const isFirst = i === 0;

    await Promise.allSettled(
      batch.map(async (file) => {
        try {
          await uploadFile(
            token,
            fullName,
            file.path,
            file.content,
            isFirst ? 'Initial commit — generated by GitForge AI' : `Add ${file.path}`
          );
          uploaded++;
        } catch (err: any) {
          console.error(`Failed to upload ${file.path}:`, err.message);
          failed.push(file.path);
        }
      })
    );

    // Small delay between batches to respect GitHub's secondary rate limits
    if (i + batchSize < files.length) {
      await new Promise(resolve => setTimeout(resolve, 200));
    }
  }

  return { uploaded, failed };
}

export const onRequestOptions: PagesFunction<Env> = async () => {
  return new Response(null, { status: 204, headers: corsHeaders() });
};

export const onRequestPost: PagesFunction<Env> = async (context) => {
  const { request, env } = context;

  try {
    let body: DeployBody;
    try {
      body = await request.json() as DeployBody;
    } catch {
      return Response.json({ error: 'Invalid JSON body' }, { status: 400, headers: corsHeaders() });
    }

    const { projectId, githubToken, repoName, repoDescription, isPrivate } = body;

    if (!projectId?.trim()) {
      return Response.json({ error: 'projectId is required' }, { status: 400, headers: corsHeaders() });
    }
    if (!githubToken?.trim()) {
      return Response.json({ error: 'githubToken is required' }, { status: 400, headers: corsHeaders() });
    }
    if (!repoName?.trim()) {
      return Response.json({ error: 'repoName is required' }, { status: 400, headers: corsHeaders() });
    }
    if (!/^[a-zA-Z0-9_.-]+$/.test(repoName)) {
      return Response.json(
        { error: 'repoName may only contain letters, numbers, hyphens, underscores and dots.' },
        { status: 400, headers: corsHeaders() }
      );
    }

    // 1. Retrieve project from R2
    const storageKey = `temp/${projectId}.json`;
    const object = await env.PROJECTS_BUCKET.get(storageKey);

    if (!object) {
      return Response.json(
        { error: 'Project not found. It may have expired. Please generate the project again.' },
        { status: 404, headers: corsHeaders() }
      );
    }

    let project: StoredProject;
    try {
      project = await object.json() as StoredProject;
    } catch {
      return Response.json({ error: 'Stored project data is corrupted.' }, { status: 500, headers: corsHeaders() });
    }

    if (!project.files?.length) {
      return Response.json({ error: 'Project contains no files.' }, { status: 400, headers: corsHeaders() });
    }

    // 2. Create GitHub repository
    let repo: GitHubRepo;
    try {
      repo = await createRepository(
        githubToken,
        repoName,
        repoDescription ?? project.description ?? '',
        isPrivate ?? false
      );
    } catch (err: any) {
      return Response.json({ error: err.message }, { status: 400, headers: corsHeaders() });
    }

    // 3. Upload files
    const { uploaded, failed } = await uploadFilesSequentially(
      githubToken,
      repo.full_name,
      project.files
    );

    // 4. Clean up R2 regardless of partial failures
    try {
      await env.PROJECTS_BUCKET.delete(storageKey);
    } catch (cleanupErr) {
      // Non-fatal: log but don't fail the response
      console.warn('R2 cleanup failed:', cleanupErr);
    }

    const result: Record<string, any> = {
      success: true,
      repoUrl: repo.html_url,
      repoName: repo.name,
      fullName: repo.full_name,
      filesUploaded: uploaded,
      totalFiles: project.files.length,
    };

    if (failed.length > 0) {
      result.warnings = `${failed.length} file(s) failed to upload: ${failed.slice(0, 5).join(', ')}${failed.length > 5 ? '...' : ''}`;
    }

    return Response.json(result, { headers: corsHeaders() });

  } catch (err: any) {
    console.error('Unhandled error in /api/deploy:', err);
    return Response.json(
      { error: err?.message ?? 'Internal server error during deployment' },
      { status: 500, headers: corsHeaders() }
    );
  }
};
